name: Build and Deploy to ECS

on:
  workflow_run:
    workflows: ["Terraform"]
    types: [completed]
  workflow_dispatch:
    
env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: abdulqayoom-registry
  ECS_CLUSTER: memos-cluster
  ECS_SERVICE: memos-container-service
  CONTAINER_NAME: memos-container

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} -f Docker/Dockerfile .


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'CRITICAL'
          exit-code: '0'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-report.sarif'

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::044005400496:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment \
            --desired-count 1 \
            --region ${{ env.AWS_REGION }}

      - name: Deployment successful
        run: |
          echo " Successfully deployed commit ${{ github.sha }}"
          echo " Image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          echo " Cluster: ${{ env.ECS_CLUSTER }}"
          echo " Service: ${{ env.ECS_SERVICE }}"
